#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     sonarSensor,         sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//






task main()
{
  int distance_in_cm = 40;   // Create variable 'distance_in_cm' and initialize it to 20(cm).
  while(SensorValue[sonarSensor] > distance_in_cm)   /* While the Sonar Sensor readings are greater */
{
	/* than the specified, 'distance_in_cm':       */

	motor[motorD] = 75;
	delay(100);
	// Motor B is run at a 75 power level
    motor[motorE] = -75;                     // Motor C is run at a 75 power level
  }

  motor[motorD] = -75;    // Motor B is stopped at a 0 power level
  motor[motorE] = 75;    // Motor C is stopped at a 0 power level
}
